CREATE TABLE plt_polls (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id         VARCHAR(36)  NOT NULL,
    creator_id      UUID         NOT NULL REFERENCES plt_users(id) ON DELETE CASCADE,
    question        VARCHAR(500) NOT NULL,
    multi_choice    BOOLEAN      NOT NULL DEFAULT false,
    closed_at       TIMESTAMPTZ,
    deadline        TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX ux_plt_polls_sync_id ON plt_polls(sync_id);
CREATE INDEX idx_plt_polls_creator_id ON plt_polls(creator_id);
CREATE INDEX idx_plt_polls_closed_at ON plt_polls(closed_at);

CREATE TABLE plt_poll_options (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id         BIGINT       NOT NULL REFERENCES plt_polls(id) ON DELETE CASCADE,
    position        SMALLINT     NOT NULL,
    option_text     VARCHAR(200) NOT NULL
);

CREATE INDEX idx_plt_poll_options_poll_id ON plt_poll_options(poll_id);

CREATE TABLE plt_poll_votes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id         BIGINT       NOT NULL REFERENCES plt_polls(id) ON DELETE CASCADE,
    option_id       BIGINT       NOT NULL REFERENCES plt_poll_options(id) ON DELETE CASCADE,
    user_id         UUID         NOT NULL REFERENCES plt_users(id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE(poll_id, option_id, user_id)
);

CREATE INDEX idx_plt_poll_votes_poll_id ON plt_poll_votes(poll_id);
CREATE INDEX idx_plt_poll_votes_user_id ON plt_poll_votes(user_id);
