version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.jetbrains.kotlin:*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
