create table messages (
    id bigint generated by default as identity primary key,
    author varchar(100) not null,
    content varchar(500) not null,
    created_at timestamp not null default current_timestamp
);
