package io.github.rygel.outerstellar.platform.extension

/**
 * Service-provider contract for JTE templates generated by platform hosts or extensions.
 *
 * Implementations are discovered through `ServiceLoader` in production rendering mode so native-image hosts can include
 * both platform templates and extension templates in the same precompiled lookup path.
 */
interface PrecompiledJteTemplateRegistry {
    val allClasses: List<Class<*>>

    fun getTemplateClass(templateName: String): Class<*>?
}
