port: 8080
jdbcUrl: "jdbc:postgresql://localhost:5432/outerstellar"
jdbcUser: "outerstellar"
jdbcPassword: "outerstellar"
devDashboardEnabled: false
devMode: false
sessionCookieSecure: true
sessionTimeoutMinutes: 30
corsOrigins: ""
