CREATE TABLE plt_message_votes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_sync_id VARCHAR(36)  NOT NULL,
    user_id         UUID         NOT NULL REFERENCES plt_users(id) ON DELETE CASCADE,
    direction       SMALLINT     NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE(message_sync_id, user_id)
);

CREATE INDEX idx_plt_message_votes_message_sync_id ON plt_message_votes(message_sync_id);
CREATE INDEX idx_plt_message_votes_user_id ON plt_message_votes(user_id);
