version: "0.1.0-SNAPSHOT"
port: 8080
jdbcUrl: "jdbc:postgresql://localhost:5432/outerstellar"
jdbcUser: "outerstellar"
jdbcPassword: "outerstellar"
appBaseUrl: "http://localhost:8080"
devDashboardEnabled: true
devMode: true
sessionCookieSecure: false
sessionTimeoutMinutes: 120
registrationEnabled: true
corsOrigins: "*"
