CREATE TABLE contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id VARCHAR(36) NOT NULL,
    name VARCHAR(200) NOT NULL,
    company VARCHAR(200),
    company_address VARCHAR(500),
    department VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_epoch_ms BIGINT DEFAULT 0 NOT NULL,
    deleted BOOLEAN DEFAULT FALSE NOT NULL,
    dirty BOOLEAN DEFAULT TRUE NOT NULL,
    version BIGINT DEFAULT 1 NOT NULL,
    sync_conflict TEXT
);

CREATE UNIQUE INDEX ux_contacts_sync_id ON contacts(sync_id);

CREATE TABLE contact_emails (
    contact_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE
);

CREATE TABLE contact_phones (
    contact_id BIGINT NOT NULL,
    phone VARCHAR(50) NOT NULL,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE
);
