-- OAuth connections for Sign in with Apple and other providers.
-- oauth_provider: e.g. 'apple', 'google'
-- oauth_subject: provider's unique user identifier (Apple 'sub' claim)
CREATE TABLE oauth_connections (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID         NOT NULL,
    provider   VARCHAR(50)  NOT NULL,
    subject    VARCHAR(255) NOT NULL,
    email      VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_oauth_provider_subject UNIQUE (provider, subject)
);

CREATE INDEX idx_oauth_connections_user ON oauth_connections(user_id);
