-- Device tokens for push notifications (FCM for Android, APNs for iOS).
-- platform: 'android' | 'ios'
-- token: FCM registration token or APNs device token
CREATE TABLE device_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID         NOT NULL,
    platform   VARCHAR(20)  NOT NULL,
    token      VARCHAR(512) NOT NULL,
    app_bundle VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_device_token UNIQUE (token)
);

CREATE INDEX idx_device_tokens_user ON device_tokens(user_id);
