-- =============================================================================
-- Initial schema — consolidated from V1-V18.
-- This is a starter project with no production data to migrate; all previous
-- incremental migrations have been collapsed into this single baseline.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Messages
-- -----------------------------------------------------------------------------
CREATE TABLE messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id             VARCHAR(36)  NOT NULL,
    author              VARCHAR(100) NOT NULL,
    content             VARCHAR(500) NOT NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_epoch_ms BIGINT       NOT NULL DEFAULT 0,
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    dirty               BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP,
    version             BIGINT       NOT NULL DEFAULT 1,
    sync_conflict       TEXT
);

CREATE UNIQUE INDEX ux_messages_sync_id  ON messages(sync_id);
CREATE        INDEX idx_messages_author  ON messages(author);
CREATE        INDEX idx_messages_created ON messages(created_at);
CREATE        INDEX idx_messages_deleted ON messages(deleted_at);

-- -----------------------------------------------------------------------------
-- Sync state (tracks last-sync epoch per domain)
-- -----------------------------------------------------------------------------
CREATE TABLE sync_state (
    state_key   VARCHAR(64) PRIMARY KEY,
    state_value BIGINT      NOT NULL
);

-- -----------------------------------------------------------------------------
-- Outbox (transactional outbox pattern)
-- -----------------------------------------------------------------------------
CREATE TABLE outbox (
    id            UUID         PRIMARY KEY,
    payload_type  VARCHAR(255) NOT NULL,
    payload       TEXT         NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at  TIMESTAMP,
    retry_count   INT               DEFAULT 0,
    last_error    TEXT,
    deleted_at    TIMESTAMP
);

CREATE INDEX idx_outbox_unprocessed ON outbox(created_at, processed_at);
CREATE INDEX idx_outbox_status       ON outbox(status);

-- -----------------------------------------------------------------------------
-- Users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id               UUID         PRIMARY KEY,
    username         VARCHAR(255) NOT NULL UNIQUE,
    email            VARCHAR(255) NOT NULL UNIQUE,
    password_hash    VARCHAR(255) NOT NULL,
    role             VARCHAR(50)  NOT NULL DEFAULT 'USER',
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_activity_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- Contacts
-- -----------------------------------------------------------------------------
CREATE TABLE contacts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id             VARCHAR(36)  NOT NULL,
    name                VARCHAR(200) NOT NULL,
    company             VARCHAR(200),
    company_address     VARCHAR(500),
    department          VARCHAR(200),
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_epoch_ms BIGINT       NOT NULL DEFAULT 0,
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    dirty               BOOLEAN      NOT NULL DEFAULT TRUE,
    version             BIGINT       NOT NULL DEFAULT 1,
    sync_conflict       TEXT
);

CREATE UNIQUE INDEX ux_contacts_sync_id ON contacts(sync_id);

CREATE TABLE contact_emails (
    contact_id BIGINT       NOT NULL,
    email      VARCHAR(255) NOT NULL,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE
);

CREATE TABLE contact_phones (
    contact_id BIGINT      NOT NULL,
    phone      VARCHAR(50) NOT NULL,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE
);

CREATE TABLE contact_socials (
    contact_id   BIGINT       NOT NULL,
    social_media VARCHAR(255) NOT NULL,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Audit log
-- -----------------------------------------------------------------------------
CREATE TABLE audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id         UUID,
    actor_username   VARCHAR(255),
    target_id        UUID,
    target_username  VARCHAR(255),
    action           VARCHAR(100) NOT NULL,
    detail           TEXT,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_log_actor   ON audit_log(actor_id);
CREATE INDEX idx_audit_log_created ON audit_log(created_at);

-- -----------------------------------------------------------------------------
-- Password reset tokens
-- -----------------------------------------------------------------------------
CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID         NOT NULL,
    token      VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP    NOT NULL,
    used       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- API keys
-- -----------------------------------------------------------------------------
CREATE TABLE api_keys (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID         NOT NULL,
    key_hash    VARCHAR(255) NOT NULL,
    key_prefix  VARCHAR(10)  NOT NULL,
    name        VARCHAR(255) NOT NULL,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_api_keys_hash ON api_keys(key_hash);
CREATE INDEX idx_api_keys_user ON api_keys(user_id);

-- -----------------------------------------------------------------------------
-- OAuth connections (Sign in with Apple, Google, etc.)
-- -----------------------------------------------------------------------------
CREATE TABLE oauth_connections (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID         NOT NULL,
    provider   VARCHAR(50)  NOT NULL,
    subject    VARCHAR(255) NOT NULL,
    email      VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_oauth_provider_subject UNIQUE (provider, subject)
);

CREATE INDEX idx_oauth_connections_user ON oauth_connections(user_id);

-- -----------------------------------------------------------------------------
-- Device tokens (FCM / APNs push notifications)
-- -----------------------------------------------------------------------------
CREATE TABLE device_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID         NOT NULL,
    platform   VARCHAR(20)  NOT NULL,
    token      VARCHAR(512) NOT NULL,
    app_bundle VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_device_token UNIQUE (token)
);

CREATE INDEX idx_device_tokens_user ON device_tokens(user_id);

-- -----------------------------------------------------------------------------
-- In-app notifications
-- -----------------------------------------------------------------------------
CREATE TABLE notifications (
    id         UUID         PRIMARY KEY,
    user_id    UUID         NOT NULL,
    title      VARCHAR(255) NOT NULL,
    body       TEXT         NOT NULL,
    type       VARCHAR(20)  NOT NULL DEFAULT 'info',
    read_at    TIMESTAMP,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_user_id    ON notifications(user_id);
CREATE INDEX idx_notifications_user_unread ON notifications(user_id, read_at);
