CREATE TABLE plt_message_votes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_sync_id VARCHAR(36)  NOT NULL,
    user_id         UUID         NOT NULL,
    direction       SMALLINT     NOT NULL CHECK (direction IN (1, -1)),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    FOREIGN KEY (message_sync_id) REFERENCES plt_messages(sync_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES plt_users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_plt_message_votes_message_user
    ON plt_message_votes(message_sync_id, user_id);
CREATE INDEX idx_plt_message_votes_message_sync_id
    ON plt_message_votes(message_sync_id);
CREATE INDEX idx_plt_message_votes_user_id
    ON plt_message_votes(user_id);
