CREATE TABLE plt_sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64)  NOT NULL,
    user_id    UUID         NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP    NOT NULL,
    FOREIGN KEY (user_id) REFERENCES plt_users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX ux_plt_sessions_token_hash ON plt_sessions(token_hash);
CREATE INDEX idx_plt_sessions_user_id ON plt_sessions(user_id);
CREATE INDEX idx_plt_sessions_expires ON plt_sessions(expires_at);
