ALTER TABLE plt_users ADD COLUMN IF NOT EXISTS language VARCHAR(10);
ALTER TABLE plt_users ADD COLUMN IF NOT EXISTS theme    VARCHAR(50);
ALTER TABLE plt_users ADD COLUMN IF NOT EXISTS layout   VARCHAR(20);
