package dev.outerstellar.starter.security

import java.util.UUID

/** Represents the user information returned after a successful OAuth handshake. */
data class OAuthUserInfo(val subject: String, val email: String?, val displayName: String?)

/** An OAuth connection record stored in the database. */
data class OAuthConnection(
    val id: Long,
    val userId: UUID,
    val provider: String,
    val subject: String,
    val email: String?,
)

/** Repository for persisting OAuth provider↔user linkages. */
interface OAuthRepository {
    /** Find an existing connection by provider name and provider-issued subject ID. */
    fun findByProviderSubject(provider: String, subject: String): OAuthConnection?

    /** Create a new connection linking a provider identity to a local user. */
    fun save(connection: OAuthConnection)

    /** List all OAuth connections for a given user. */
    fun findByUserId(userId: UUID): List<OAuthConnection>
}

/**
 * Strategy interface for OAuth 2.0 identity providers.
 *
 * Implementations must be stateless. State parameters (CSRF nonces) are generated by the caller and
 * must be passed through unchanged.
 */
interface OAuthProvider {
    /** Stable identifier for this provider, e.g. "apple". */
    val name: String

    /**
     * Return the authorization URL the browser should be redirected to.
     *
     * @param state an opaque, random CSRF token generated by the caller
     * @param redirectUri the callback URL registered with the provider
     */
    fun authorizationUrl(state: String, redirectUri: String): String

    /**
     * Exchange an authorization [code] for an access token and extract user info.
     *
     * @throws OAuthException if the exchange fails or the token is invalid
     */
    fun exchangeCode(code: String, state: String, redirectUri: String): OAuthUserInfo
}

/** Thrown when an OAuth flow fails (token exchange error, invalid state, etc.). */
class OAuthException(message: String, cause: Throwable? = null) : RuntimeException(message, cause)
