package io.github.rygel.outerstellar.platform.security

import io.github.rygel.outerstellar.platform.persistence.OAuthUserInfo

/**
 * Strategy interface for OAuth 2.0 identity providers.
 *
 * Implementations must be stateless. State parameters (CSRF nonces) are generated by the caller and must be passed
 * through unchanged.
 */
interface OAuthProvider {
    /** Stable identifier for this provider, e.g. "apple". */
    val name: String

    /**
     * Return the authorization URL the browser should be redirected to.
     *
     * @param state an opaque, random CSRF token generated by the caller
     * @param redirectUri the callback URL registered with the provider
     */
    fun authorizationUrl(state: String, redirectUri: String): String

    /**
     * Exchange an authorization [code] for an access token and extract user info.
     *
     * @throws OAuthException if the exchange fails or the token is invalid
     */
    fun exchangeCode(code: String, state: String, redirectUri: String): OAuthUserInfo
}

/** Thrown when an OAuth flow fails (token exchange error, invalid state, etc.). */
class OAuthException(message: String, cause: Throwable? = null) : RuntimeException(message, cause)
